version: '3.4'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sync_binlog=0 --innodb_doublewrite=OFF  --innodb-flush-log-at-trx-commit=0 --innodb-flush-method=nosync
    environment:
      MYSQL_DATABASE: lucid
      MYSQL_USER: virk
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
  pg:
    image: postgres:11
    environment:
      POSTGRES_DB: lucid
      POSTGRES_USER: virk
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
